### ISSUE TITLE
QUIC Transport

### ISSUE THREAD

**Issue by gedw99** [gu-io/gu#14]
QUIC is an alternative to HTTP2.

It uses UDP, and is basically a replacement for webrtc.
Its very easy to use and has no dependencies.

Why is it good ?
Very fast 
Makes it very easy to do bi-directional communications.
Allows peer to peer scenarios.

Where is it supported ?
Chrome supports it. Other browser do not.
QT Webview can use it because its not reliant on a browser.

https://github.com/lucas-clemente/quic-go

**Comment by influx6** [comment]
Moving this to https://github.com/influx6/octo repo.
