### ISSUE TITLE
caching / service worker

### ISSUE THREAD

**Issue by gedw99** [gu-io/gu#15]
At the moment there is no caching.

The example "greeter" takes 41 seconds to initially load over a good 3G connection.
Thats just life with gopherjs, and is fine, because this is designed to build applications, and not just websites.

Seems right now that gopherjs caching is broken.
https://github.com/gopherjs/gopherjs/issues/568

I am thinking that we can use service worker anyway, and so not be dependent on traditional web server / web browser caching.
Here is some good background about Service Worker:
https://developers.google.com/web/fundamentals/getting-started/codelabs/debugging-service-workers/

Browser Support:
http://caniuse.com/#feat=serviceworkers
Its not a great story here. Edge and Safari do not support it.
But Chrome is now the dominant browser, so its still work doing this perhaps ? Or we should concentrate on the QT Webview instead ?

Here is how to use Service Worker to good effect. Your basically breaking up the app to laod in stages, and you can push to the Browser, whilst the user is doing something else. 
https://www.polymer-project.org/1.0/toolbox/server

**Comment by influx6** [comment]
Interesting, I guess for now we can look into how polymer does it then graft in as much as needed.

**Comment by influx6** [comment]
My major aim is to concentrate on QT then tack this.

**Comment by influx6** [comment]
We will use [GopherJS#559](https://github.com/gopherjs/gopherjs/issues/559) for reference as per gopherjs caching issues.

**Comment by gedw99** [comment]
Sounds good.

About Qt.

Do you have Qt I stalled ? Gonna need it.
Then there open/Qt repo.

Then I can help build the Qt driver.

**Comment by influx6** [comment]
Yes QT is installed.

**Comment by gedw99** [comment]
i was having a think about this and have a game plan.

PRPL pattern i think is not what we want and not what we can do. We cant do it because gopherjs wants to load one single file. Its compiled, unlike polymer which is loosely coupled.

SO i propose this:
1. We provide a "splash/ loading page" which is not using gopherjs and loads on startup straight away.
2. We use the new Server PUSH thats in go 1.8 to background push the main.js that is the gopherjs code. When its loaded the "splash / loading page" is removed.
3. We make sure we do proper caching headers so that the browser does cache things, and so the background PUSH only happens if needed.

i feel this is easy and maps better to how gopherjs works and also to the use cases for which it will be used. 

also it will be pretty fast to try this out on the greeter example.

Curious what you think.

**Comment by influx6** [comment]
Well give it a go. My thoughts are focused on QT now to be honest.

**Comment by influx6** [comment]
But what happens when the browser does not support server push ?

**Comment by gedw99** [comment]
Then we are screwed. Good point.
I think we can just not use push.
The loading page can simply call the main big JS file.
Should work fine.

When someone wants to build really large applications they can just write
them as complexly seperate app. It means the golang primitives get reloaded
many times but it's fine as long as we have the splash loading page.

Best way to this about it is just like how on mobiles you have small apps
and you use intents between them. This is no routing between them.
So we take the same approach with the web apps.

Once you have made some more examples I can start to understand GU more and
put in some big examples to use the design above.

**Comment by influx6** [comment]
Ok thats sounds like a plan.

**Comment by influx6** [comment]
Adding html template which generates an html page with a loading screen when using js driver.
