### ISSUE TITLE
diagram

### ISSUE THREAD

**Issue by gedw99** [gu-io/gu#24]
would be good to have a basic diagram shows the logical architecture of the system.

is some ways the flux patter is what Gu uses, as well as others.
So i am linking that diagram here to just show the idea:
https://github.com/facebook/flux

Making diagrams with https://github.com/jgraph/drawio-github is the way to go

**Comment by influx6** [comment]
Nope it doesnt use flux bro. No stores, just a pubsub system. Not much flux
in there to be honest.

**Comment by influx6** [comment]
Remember its a UI library that has no dataflow standards ;)

**Comment by gedw99** [comment]
Ok.

Well the pubsub system is nice because it's highly adaptable, and I am
guessing this is your intent ?

If you make another example to show a bit more of the component composition
with some events between it would be good.

G

**Comment by influx6** [comment]
You want an example of a parent component speaking to a component it
composes?

**Comment by gedw99** [comment]
Yes. Just something to show composition. Keep it stupid simple for now.

Just as a starting point.

**Comment by influx6** [comment]
This will be resolved on https://github.com/gu-io/example repo
