### ISSUE TITLE
explore shiny

### ISSUE THREAD

**Issue by gedw99** [gu-io/gu#27]
shiny needs a GU liek Tree layout engine. Everyone is doing it imperitivly, and GU can do it by configuration.
Can even use shiny to build a WYSIWYG layout tool wth GU, by just used JSON and serialisation.
Thats obviously not what you shoudl do first though. But you could built the equivalent of QT Designer for Shiny.

---

examples:

https://github.com/jnjackins/graphics

https://github.com/aarzilli/nucular

Not shiny but 3d
https://github.com/fogleman/fauxgl

--

Why ?
Shiny can run on Desktops and Mobiles. You can and others have built Android Apps. Not sure abot how far i got with IOS apps.
Its like QT (immediate mode rendering).
There is audio support too.

--

Material Design.
they started it off but did not finish it.
https://github.com/golang/exp/tree/master/shiny/materialdesign

---
 you can also make it render to a browser. Yeah.
Shurcool did some work on making a driver for shny which essentially targeted the Canvas In Web.
This is pretty amazing because you could have the same Materials Design GUi work on both Open GL and web with no code changes. The reason being because they are both workng with the exact same primitives - vector based Rectangles, Curves & Fonts.
Food for thought.

---

Other stuff needed to complete the ability to build real world apps.

Notifications:
Web - https://github.com/shurcooL/notificationsapp
Shiny - just need to tap into Android and IOS Notifications. 
Qt does it this way
http://doc.qt.io/qt-5/qtandroidextras-notification-example.html
Qt/Golang: https://github.com/therecipe/qt/tree/master/internal/examples/androidextras/notification

Sharing:
Yes you need to allow Apps to tak to other apps fro Desktop and Mobiles.
For web there is now a Spec being driven by Google.
The Ballista project outlined at https://github.com/chromium/ballista is being developed in small pieces, the first two of which are:
https://github.com/WICG/web-share, and
https://github.com/WICG/web-share-target

For Desktop there is some support. The  github repos above outline how to make sharing work on Desktops and Mobiles.

Systems Tray host:
Yep sometimes you need this. Its for when you need a long running Service with a GUI.
Desktop:
https://github.com/shurcooL/trayhost
QT:
Has support for it.

IPC:
To make the Sharing, Trayhost and Notifications work, you just need a golang cross platform Lib for desktop.
this allows one App to call another directly, Or an app to call a Service to act as a broker / pubsub thingy. 
In golang there are a few, just cant find a cross platform one this morning :)

---

Testing
When you have a project like this you need to test from the top down.
this does it with golang
https://github.com/go-vgo/robotgo
impresive workd

**Comment by joeblew99** [comment]
Want to mention this one.
It's really the best most mature example of what we are aiming for out there.

https://github.com/dskinner/material

It's been going for a while getting built up.
It is using gomobile, not shiny.
There has been lots of debate about which to use :) they kind of overlap.

He also has sound. Yeah often forgotten about.

**Comment by influx6** [comment]
Awesome, thanks for the update will get to these asap.

**Comment by influx6** [comment]
Moved to https://github.com/gu-io/shiny/issues/1
