### ISSUE TITLE
go get failing for me

### ISSUE THREAD

**Issue by joeblew99** [gu-io/gu#31]
go get github.com/gu-io/gu/...
package github.com/gu-io/gu/events: cannot find package "github.com/gu-io/gu/events" in any of:
	/usr/local/opt/go/libexec/src/github.com/gu-io/gu/events (from $GOROOT)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/events (from $GOPATH)

**Comment by influx6** [comment]
There are no more references to `github.com/gu-io/gu/events` in code. Could you please, delete old source in your GOPATH, GOPATH/pkg as well.

**Comment by joeblew99** [comment]
ok that helped. i cleaned the pkg and src

now i get 👍 
x-MacBook-Pro:github.com apple$ go get github.com/gu-io/gu/
# github.com/gu-io/gu/trees/themes/styleguide
gu-io/gu/trees/themes/styleguide/style.go:578: undefined: colors.IsHex

**Comment by influx6** [comment]
This seem to related with an external package dependency which is related
to `influx6/faux/colors` pkg. Please delete all `influx6` and `gu-io`
directories in your GOPATH/src.

I would like to have the dependencies vendored but I fear, gu-io should
always use latest changes and not vendored changes, more so, we can not
vendor gopherjs has this will cause errors.

Best Regards,
Alex.

Chief Information Officer (CIO)
Dream Bench Technologies
www.dreambench.io (alex.ewetumo@dreambench.com)

**Comment by joeblew99** [comment]
i think there were lots of nasties with vendoring with gopherjs.
but worth a try on the examples project. can vendor gu in the examples project and see if she blows up. quick and easy to try

**Comment by joeblew99** [comment]
so got this working...
