### ISSUE TITLE
layout 

### ISSUE THREAD

**Issue by joeblew99** [gu-io/gu#35]
I was playing around with ebiten, as he has a UI example:
https://github.com/hajimehoshi/ebiten/tree/master/examples/ui
- It runs on web, desktop and mobile

Then i was comparing it with dskinners UI example:
https://github.com/dskinner/x/tree/master/glw
- This runs on desktop and mobile.

You shoudl have a try. Very easy to get gong on desktop for sure.
The two are so very different.

But what i was really interested in was how to do Layout.
Ebiten has no layout helpers.
dskinner is currently using the flexbox built into shiny. 

Now i think cssgrid is the way to go for GU, but also for the opengl stuff of dskinner and even ebiten.

what this: https://www.youtube.com/watch?v=7kVeCqQCxlk

Jump to the 18 minute point for the juicy bits :)

I think a golang version of css grid will not be too hard either because its really embraces simplicity.

**Comment by influx6** [comment]
Ok. Will do.

**Comment by influx6** [comment]
Have decided to spun a different project all together for mobile. Gu will stick to just gopherjs only.
