### ISSUE TITLE
hello example fails to build 

### ISSUE THREAD

**Issue by gedw99** [gu-io/gu#6]
from:
src/github.com/gu-io/gu/examples/hello

x-MacBook-Pro:hello apple$ gopherjs build -o hello.go hello.js
cannot find package "hello.js" in any of:
	/usr/local/go/src/hello.js (from $GOROOT)
	/Users/apple/workspace/go/src/hello.js (from $GOPATH)

x-MacBook-Pro:hello apple$ gopherjs serve
serving at http://localhost:8080 and on port 8080 of any available addresses
cannot find package "github.com/influx6/gu/design" in any of:
	/Users/apple/workspace/go/src/github.com/gu-io/gu/vendor/github.com/influx6/gu/design (vendor tree)
	/usr/local/go/src/github.com/influx6/gu/design (from $GOROOT)
	/Users/apple/workspace/go/src/github.com/influx6/gu/design (from $GOPATH)

**Comment by influx6** [comment]
Example updated. Please retry

**Comment by gedw99** [comment]
still fails

**Comment by influx6** [comment]
This is because you are issuing the commands in the wrong order.

`gopherjs build -o hello.js hello.go`
