### ISSUE TITLE
restfull boxes segmentation faults

### ISSUE THREAD

**Issue by gedw99** [gu-io/gu#7]
once i hit the browser the segmentation fault fires.

cd server/
x-MacBook-Pro:server apple$ go run main.go
HTTP : "2016-12-20 17:13:26.669409081 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:26.669420101 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:26.669375695 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:26.66939287 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:28.670701818 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:30.670176352 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:31.669592926 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:32.058749608 +0000 UTC" : Content{text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8} : Method{GET} : URI{/}
HTTP : "2016-12-20 17:13:32.069821033 +0000 UTC" : Content{*/*} : Method{GET} : URI{/assets/restful.js}
HTTP : "2016-12-20 17:13:32.668417638 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
HTTP : "2016-12-20 17:13:32.668569468 +0000 UTC" : Content{} : Method{GET} : URI{/colors}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x20cc40]

goroutine 65 [running]:
panic(0x4dcd00, 0xc42000c0b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gu-io/gu/design.newResource.func1(0xe580a8, 0xc42001d5c0, 0xc4201c8ba0, 0x26, 0x0, 0x0)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/design/design.go:355 +0xa0
reflect.Value.call(0x4ba960, 0xc4201c11a0, 0x13, 0x58ac60, 0x4, 0xc420303df0, 0x1, 0x1, 0xfd388, 0x4ff980, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x4ba960, 0xc4201c11a0, 0x13, 0xc420303df0, 0x1, 0x1, 0x4ff980, 0x4ff980, 0xc4202bf601)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/gu-io/gu/dispatch/mque.(*mqueSub).Run(0xc4201c8cc0, 0x4ff980, 0xc4204322a0, 0xa4fee0, 0x4ff980)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/dispatch/mque/mque.go:194 +0x1f1
github.com/gu-io/gu/dispatch/mque.(*MQue).Run(0xc4201453c0, 0x4ff980, 0xc4204322a0)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/dispatch/mque/mque.go:49 +0x141
github.com/gu-io/gu/dispatch.Dispatch(0x4ff980, 0xc4204322a0)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/dispatch/dispatcher.go:23 +0x41
github.com/gu-io/gu/design.DoView.func1()
	/Users/apple/workspace/go/src/github.com/gu-io/gu/design/design.go:624 +0x104
github.com/gu-io/gu.(*reactive).Publish(0xc4201c1460)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/gu.go:82 +0x49
github.com/gu-io/gu.(Reactive).Publish-fm()
	/Users/apple/workspace/go/src/github.com/gu-io/gu/views.go:53 +0x2f
github.com/gu-io/gu.(*reactive).Publish(0xc4201c1420)
	/Users/apple/workspace/go/src/github.com/gu-io/gu/gu.go:82 +0x49
created by github.com/gu-io/gu/examples/restfulboxes/app.(*RestfulBox).update
	/Users/apple/workspace/go/src/github.com/gu-io/gu/examples/restfulboxes/app/app.go:64 +0x1bb
exit status 2

**Comment by influx6** [comment]
Issues with segmentation has been fixed and code updated. Please pull and re-run
